### ISSUE TITLE
Implement bearer token refresh

### ISSUE THREAD

**Issue by pke** [lev-kuznetsov/node-fetch-middleware#10]
I wonder if it would be possible to implement a bearer token refresh middleware that in itself would benefit from the other registered middlewares like json response parsing.

I think its rather difficult as from within the bearer middleware we do not have access to the outer fetch to perform our refresh request (and get its response parsed into `response.parsed`) or do you have an idea @lev-kuznetsov?

**Comment by lev-kuznetsov** [comment]
I'm not sure I understand what you mean here. You would need the bearer token to perform the request and to get the token you would usually need to make a completely different request. So here's an example with auth0 flow (off the top of my head):

```typescript
import {bearer, json, compose, cache} from 'node-fetch-middleware'

const fetchToken = compose([cache(key: () => 'foobar', ttl: () => 60 * 60 * 10), json])

async function token () => {
  const {parsed: {access_token}} = await fetchToken('https://foobar.auth0.com/', {
    method: 'POST', json: {
      grant_type: 'client_credentials',
      client_id: 'foobar',
      client_secret: 'barfoo',
      audience: 'https://foobar'
    }
  })
  return access_token
}

const fetch = compose([
  bearer({
    provider: token
  }), json
])

fetch('https://foobar.com/yolo') // <- will get the token
```

**Comment by pke** [comment]
Thanks for your swift response.
Yes this will get the access token but I was wondering about the moment the access token times out and you would need a refresh token as a response to any of the API calls returning 401.

**Comment by lev-kuznetsov** [comment]
I'm trying to remember how those flows work, I guess you make a request to your target API first without a token and get a 401 with info on where to get the token? I suppose the `bearer` I ship doesn't support that flow but you can make one yourself:

```typescript
const bearer = async (url, init, next) => {
  const response = await next(url, init)
  const {status} = response
  if (status !== 401) return response
  // you got your 401 now; it's your stuff you may assume json middleware here
  const {stuff} = response.parsed
  const token = stuff // do whatever you want
  return next(url, {...init, headers: {...(init ?? {}).headers, 'Authorization': `Bearer ${token}`})
}
```

Something like that.

**Comment by pke** [comment]
I'd have to remember that I'm refreshing. 
But beside that, would calling next invoke the whole middleware chain or only the ones that were added after the bearer middleware?

**Comment by lev-kuznetsov** [comment]
It will call all the next middleware in the chain again. In the above example:

```typescript
const bearer = async (url, init, next) => {/* ... */}

const fetch = compose([bearer, json])
```
It will call json again, `next` is just a wrapper around whatever is after yourself in the array.

**Comment by pke** [comment]
Yea this works, maybe we add this behaviour to the bearer mw? It could just call the `provider` in case of an 401 to try to fetch a new token. If that fails the mw should forward the initial error upstream.
